steps:
  deploy-api:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/www/solvpath_pri_sch:/host_env
    commands:
      # Use the absolute path of the mounted file directly
      - docker compose -f /host_env/docker-compose.yml down
      - docker compose -f /host_env/docker-compose.yml up -d --build

when:
  - branch: main
    event: push