services:
  app1:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3910:3000"
    environment:
      - PORT=3000
    restart: always
    depends_on:
      - redis
  app2:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3920:3000"
    environment:
      - PORT=3000
    restart: always
    depends_on:
      - redis
  app3:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3930:3000"
    environment:
      - PORT=3000
    restart: always
    depends_on:
      - redis


  redis:
      image: redis:7-alpine
      container_name: redis_cache
      restart: always
      ports:
        - "6379:6379" # Only needed if you want to access Redis from your host machine
        
      volumes:
        - redis_data:/data

# Persistent storage so your data survives container restarts
volumes:
  redis_data: