services:
  app1:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3910:3000"
    environment:
      - PORT=3000
      - REDIS_URL=${REDIS_URL}
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      

  app2:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3920:3000"
    environment:
      - PORT=3000
      - REDIS_URL=${REDIS_URL}
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app3:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3930:3000"
    environment:
      - PORT=3000
      - REDIS_URL=${REDIS_URL}
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
