services:
  app1:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3910:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://127.0.0.1:6379
    restart: always
    network_mode: host
      

  app2:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3920:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://127.0.0.1:6379
    restart: always
    network_mode: host

  app3:
    build: .
    image: solvpath-pri:latest
    ports:
      - "3930:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://127.0.0.1:6379
    restart: always
    network_mode: host

